### ISSUE TITLE
Add speciesProfile information

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-fishes-checklist#14]
Do we know the following information for the fishes in this dataset?

* isMarine
* isFreshwater
* isTerrestrial: yes, `false` for all.

If so, I would add habitat information to the source file, include it in the description extension and populate the speciesProfile.

**Comment by LienReyserhove** [comment]
All species are freshwater species (double-checked with Hugo). I will integrate this in the speciesProfile information.
