### ISSUE TITLE
Update scientific names to their accepted name?

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-fishes-checklist#17]
The following taxa are considered synonyms by GBIF. For each: ask Hugo if it's OK to a) update in the xls our scientific name to the accepted species or b) keep our current species name

- [ ] `Aspius aspius` (https://www.gbif.org/species/2360181) is considered a synonym of `Leuciscus aspius` (https://www.gbif.org/species/5851603)
- [ ] `Acipenser guldenstaedti`... actually written as `Acipenser güldenstaedti` (https://www.gbif.org/species/2402131) is considered a synonym of `Acipenser gueldenstaedtii` (https://www.gbif.org/species/2402129)

**Comment by LienReyserhove** [comment]
I asked Hugo, he agrees to update the scientific names. Will adapt this asap.

**Comment by peterdesmet** [comment]
These two synonyms are now handled in the verification of the unified checklist (accepting the proposed synonymy by GBIF). There is no longer a need to update these in this checklist. In fact, it might be better to keep the original names. Closing issue.
