### ISSUE TITLE
Strange heading in .Rmd

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-fishes-checklist#8]
The header of the [dwc_checklist.Rmd](https://github.com/trias-project/alien-fishes/blob/master/src/dwc_checklist.Rmd) is rather odd. Needs to be checked later (by myself or @peterdesmet)

**Comment by peterdesmet** [comment]
Is this still an issue?

**Comment by peterdesmet** [comment]
Looks OK, closing.
